apiVersion: v1
baseDomain: aws-ocpcluster.click
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 1
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 1
metadata:
  creationTimestamp: null
  name: swetha
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: us-east-1
publish: External
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfNzdmOGQ2NjY0ZTA3NGMxOThkOWQ5YTU5YTUxYmNjZGM6UUZRQlcySUNHSFBDTVcyNkQ2RTc3NUZKOFpYMU1IQ05HSEc4NERJQThIWTI2T0ZUWkk5UzRLTFpXSkxOVDNGVQ==","email":"madhu.chenna@ibm.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfNzdmOGQ2NjY0ZTA3NGMxOThkOWQ5YTU5YTUxYmNjZGM6UUZRQlcySUNHSFBDTVcyNkQ2RTc3NUZKOFpYMU1IQ05HSEc4NERJQThIWTI2T0ZUWkk5UzRLTFpXSkxOVDNGVQ==","email":"madhu.chenna@ibm.com"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLTJhOTkzYTk1LTBmOWMtNDFiMy1iMWZiLWRjYjg0NDI5Y2M4ODpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmpPR0V3TXpkaU5UWXhabVUwTm1FMllXWmtPVEkyWVRBNVlUWmhOR0V5TlNKOS52NVhWckd4c041X2l3QmhmV2dnMm1wWDF1TmVOREt5ZFFvaVItN2ZhNlFuOHpLSEE2dUJKbV9XeFNiVFVYRm1pWmRmVU9uZVhJQi1tcWdHelNWbWZkQm5YdURGbWRpNUdIUC05NjRuMlBTQTh0dk9NaGZTSWVLZTNSb01nR2JIRVVNWHAyQmtTVnFNUVprUjdGZ1J6bTZBMlZCRGRKNDNQMWpYQlFvTFRZQTc2Y2FqOE5OMUwwVjgweFIwbHZYVkNWbUNJNzY2NmhGZTBTdnRDalYwYzZKdWJ1a01CWDZHamdBaWhoeFp4NUJIYV9WbU43aEI1WkVUd194NDBLd0pHN1BUTW1VVGNVY01SSnViOFZ4RTZmaFRJVkl4UVM5WXNSX1lZcjN3U0ZpZjNWaThseTBLdzloT0ZMWHJ0SmF1RktoVk1SZU1GM0ppbU9Oc2Q2UDY4OWVuQ2NKcXVtcW1xMGgzLWVIVlVERXZPSkRJUXlNX2JkMF9jTzV0cVBtdjE1VXhLZk5ab3M5aWNTU0VUdTd2OE1iOEhHdWZyNnRVTmNTWWo1UFJHalNSalZmaUZGb01KVFdxckRVMmJidENnMmdwNkdocFhJWEtJQ0hLS3JBRHNZOFVkVWJhMlR4Wk9BNDBES09DbTJHUTkyMF9URE9UN05WZU95V0VJSi1jdzdna1ZtOWNMN1ZqbWNtZUlRUjZqMU9keG51cHdMZmxOMS0yT19hR3VDb2pYVFNRN29vaVVYdUl5Y1NEQVljdzNIcTdJTGZWaVBwcE1rc2NiNzhTTV9Wc2owWENMcC1abjdyS3BoVVNoYjVoTHEzRjl3WG5tbHJ6Q2kzVjdKX2dFUkZkQjRNSnN5eW1ZUFJ4YVZsOFd6Qno4a3RoSjh2UzRiM1g5YTAybkN1SQ==","email":"madhu.chenna@ibm.com"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLTJhOTkzYTk1LTBmOWMtNDFiMy1iMWZiLWRjYjg0NDI5Y2M4ODpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmpPR0V3TXpkaU5UWXhabVUwTm1FMllXWmtPVEkyWVRBNVlUWmhOR0V5TlNKOS52NVhWckd4c041X2l3QmhmV2dnMm1wWDF1TmVOREt5ZFFvaVItN2ZhNlFuOHpLSEE2dUJKbV9XeFNiVFVYRm1pWmRmVU9uZVhJQi1tcWdHelNWbWZkQm5YdURGbWRpNUdIUC05NjRuMlBTQTh0dk9NaGZTSWVLZTNSb01nR2JIRVVNWHAyQmtTVnFNUVprUjdGZ1J6bTZBMlZCRGRKNDNQMWpYQlFvTFRZQTc2Y2FqOE5OMUwwVjgweFIwbHZYVkNWbUNJNzY2NmhGZTBTdnRDalYwYzZKdWJ1a01CWDZHamdBaWhoeFp4NUJIYV9WbU43aEI1WkVUd194NDBLd0pHN1BUTW1VVGNVY01SSnViOFZ4RTZmaFRJVkl4UVM5WXNSX1lZcjN3U0ZpZjNWaThseTBLdzloT0ZMWHJ0SmF1RktoVk1SZU1GM0ppbU9Oc2Q2UDY4OWVuQ2NKcXVtcW1xMGgzLWVIVlVERXZPSkRJUXlNX2JkMF9jTzV0cVBtdjE1VXhLZk5ab3M5aWNTU0VUdTd2OE1iOEhHdWZyNnRVTmNTWWo1UFJHalNSalZmaUZGb01KVFdxckRVMmJidENnMmdwNkdocFhJWEtJQ0hLS3JBRHNZOFVkVWJhMlR4Wk9BNDBES09DbTJHUTkyMF9URE9UN05WZU95V0VJSi1jdzdna1ZtOWNMN1ZqbWNtZUlRUjZqMU9keG51cHdMZmxOMS0yT19hR3VDb2pYVFNRN29vaVVYdUl5Y1NEQVljdzNIcTdJTGZWaVBwcE1rc2NiNzhTTV9Wc2owWENMcC1abjdyS3BoVVNoYjVoTHEzRjl3WG5tbHJ6Q2kzVjdKX2dFUkZkQjRNSnN5eW1ZUFJ4YVZsOFd6Qno4a3RoSjh2UzRiM1g5YTAybkN1SQ==","email":"madhu.chenna@ibm.com"}}}'
sshKey: |
  ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINn+9rtC594PYIT09/9LD8csN0eJAaDUWZlxlrStgGLp madhuchenna@Madhus-MBP.hsd1.ga.comcast.net
